"""
Wazuh Alert Dashboard - entry point.

Everything lives in the installable `dashboard_core` package; this file only
resolves the bind address and starts the server.

RUNNING:
    pip install -e .        # installs deps from pyproject.toml + this package
    python main.py

    UI:            http://localhost:5000  (login/registration required)
    Webhook URL:   http://localhost:5000/wazuh-webhook
    API docs:      http://localhost:5000/docs   (auto-generated by FastAPI)
"""

from dashboard_core.app import app
from dashboard_core.storage import load_run_host_port
import uvicorn

if __name__ == "__main__":
    host, port = load_run_host_port()
    uvicorn.run(app, host=host, port=port)
