#!/var/ossec/framework/python/bin/python3
"""
custom-webhook.py
==================
POSTs the alert generated by Wazuh AS-IS (with all its fields, including
rule, agent, full_log) to the target webhook URL.

What makes this different from built-in integrations like 'slack': the
'slack' script reformats the payload into a Slack-specific message format
(text/attachments), which is why our dashboard couldn't find the
rule/agent fields and showed "-". This script sends the raw alert JSON
unmodified.

INSTALLATION:
    sudo cp custom-webhook /var/ossec/integrations/
    sudo cp custom-webhook.py /var/ossec/integrations/
    sudo chown root:wazuh /var/ossec/integrations/custom-webhook*
    sudo chmod 750 /var/ossec/integrations/custom-webhook*
    sudo systemctl restart wazuh-manager

ossec.conf:
    <integration>
      <name>custom-webhook</name>
      <hook_url>http://YOUR-DASHBOARD-ADDRESS:5000/wazuh-webhook</hook_url>
      <level>10</level>
      <alert_format>json</alert_format>
    </integration>
"""

import json
import os
import sys
import time

try:
    import requests
except ImportError:
    print("ERROR: the 'requests' module was not found.")
    print("Install it with: /var/ossec/framework/python/bin/pip3 install requests")
    sys.exit(1)

# Wazuh calls this script with the following arguments:
#   argv[1] = path to the alert file (temporary .alert file)
#   argv[2] = API key / user (not used for a plain webhook, empty string)
#   argv[3] = hook_url (the address defined in ossec.conf)
#   argv[4] = (optional) extra options

LOG_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.realpath(__file__))), "logs"
)
LOG_FILE = os.path.join(LOG_DIR, "integrations.log")


def log(message: str) -> None:
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
    try:
        with open(LOG_FILE, "a") as f:
            f.write(f"{timestamp} custom-webhook: {message}\n")
    except Exception:
        pass  # don't let a logging failure stop the script


def main(args):
    if len(args) < 4:
        log("ERROR: missing arguments, check the integration block in ossec.conf.")
        sys.exit(1)

    alert_file_path = args[1]
    webhook_url = args[3]

    with open(alert_file_path) as f:
        alert_json = json.load(f)

    try:
        response = requests.post(
            webhook_url,
            headers={"Content-Type": "application/json"},
            json=alert_json,
            timeout=10,
        )
        log(f"sent, HTTP status code={response.status_code}")
    except Exception as e:
        log(f"ERROR: could not send request - {e}")
        sys.exit(1)


if __name__ == "__main__":
    main(sys.argv)
